[google]
GOOGLE_API_KEY = "AIzaSyAyzM6ugbQivLuZivMnIBf0S7QzGaSiivM"

[vector_db]
VECTOR_DB_PATH = "./vector_store"
FAISS_INDEX_PATH = "./vector_store/faiss_index.index"
METADATA_PATH = "./vector_store/metadata.json"

[text_processing]
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
MAX_FILE_SIZE_MB = 50

[gemini]
EMBEDDING_MODEL = "models/embedding-001"
EMBEDDING_TASK_TYPE = "retrieval_document"
